CREATE TABLE [dbo].[STAGE_RPO](
	PRODUTO NVARCHAR(MAX),
	UF NVARCHAR(2),
	SEMANA INT,
	MARGEM_LIQUIDA_REAL_PC FLOAT,
	PRECO FLOAT(2),
	VENDAS_REAIS_QTDE INT,
	VENDAS_REAIS_MONETARIO FLOAT(2),
	MARGEM_LIQUIDA_REAL_MONETARIO FLOAT,
	VENDA_LIQUIDA_REAL_MONETARIO FLOAT(2),
	CMV FLOAT,
	CMV_UNIT FLOAT,
	DPPSIC INT,
	NOBS NVARCHAR(10),
	GRUPO INT
)